@BaseAddress = http://localhost:5012

### Get all todo items
GET {{BaseAddress}}/api/todoitems

### Get a specific todo item by ID
GET {{BaseAddress}}/api/todoitems/1

### Create a new todo item
POST {{BaseAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

### Update an existing todo item
PUT {{BaseAddress}}/api/todoitems/1
Content-Type: application/json

{
  "id": 1,
  "name": "walk dog",
  "isComplete": false
}

### Delete a todo item
DELETE {{BaseAddress}}/api/todoitems/1


