@BaseAddress = http://localhost:5012

GET {{BaseAddress}}/weatherforecast/
Accept: application/json

###

POST {{BaseAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###
