namespace TodoApi.Database;

/// <summary>
/// Entity representing a TodoItem in the database
/// </summary>
public class TodoItem
{
    /// <summary>
    /// Unique Key for the TodoItem, generated by the database when the item is created
    /// </summary>
    public long Id { get; set; }
    /// <summary>
    /// Name of the TodoItem
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// Indicates whether the TodoItem is complete
    /// </summary>
    public bool IsComplete { get; set; }
}