using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TodoApi.Database;

/// <summary>
/// Entity representing a TodoItem in the database
/// </summary>
public class TodoItem
{
    /// <summary>
    /// Unique Key for the TodoItem, generated by the database when the item is created
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public required long Id { get; set; }
    /// <summary>
    /// Name of the TodoItem
    /// </summary>
    public string? Name { get; set; }
    /// <summary>
    /// Indicates whether the TodoItem is complete
    /// </summary>
    public required bool IsComplete { get; set; }
}